name: Deploy Notes

# run every 12 hours, on changes to default branch, and manually
on:
  push:
    branches:
      - v4
  schedule:
    - cron: 0 */12 * * *
  repository_dispatch:

concurrency: # prevent concurrent deploys doing strange things
  group: deploy
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Build and deploy Quartz site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Quartz
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Checkout notes
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.NOTES_REPO }}
          token: ${{ secrets.NOTES_REPO_PAT }}
          path: content
      - name: Build Quartz
        run: |
          npm ci
          npx quartz build
      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_API_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_API_CLIENT_SECRET }}
          tags: ${{ secrets.TS_TAG }}
      - name: Configure SSH known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
      - name: Deploy Quartz
        run: |
          rsync -avz --delete -e ssh public/ deploy@${{ secrets.QUARTZ_HOST }}:${{ secrets.QUARTZ_CONTENT_PATH }}
      # - name: Purge Bunny CDN cache
      #   uses: ayeressian/bunnycdn-storage-deploy@v2.2.2
      #   with:
      #     source: ""
      #     destination: ""
      #     storageZoneName: ""
      #     upload: "false"
      #     remove: "false"
      #     accessKey: "${{ secrets.BUNNY_API_KEY }}"
      #     pullZoneId: "${{ secrets.BUNNY_ZONE_ID }}"
      #     purgePullZone: "true"
